server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: jumper-test
  jpa:
    show-sql: true
  datasource:
#    username: opencentor_test_user
#    password: aQrgxf3ZA6LvyuN9
#    url: jdbc:mysql://10.72.4.16:3306/opencentor?serverTimezone=GMT%2B8&autoReconnect=true&socketTimeout=30000&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: pers_tmp_user
    password: pers_tmp@123
    url: jdbc:mysql://10.72.4.16:3306/ha_hygeia?serverTimezone=GMT%2B8&autoReconnect=true&socketTimeout=30000&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      table-underline: true
      logic-not-delete-value: 0
      logic-delete-value: 1

jumper:
  enabled: true
  #  package_mapper: com.ck.db.po
  SqlCompile:
    controller: true
